### PR TITLE
Add support for German language

### PR DESCRIPTION
**Pull request by marlemion**
Hi, I have created and implemented a file for German translation

### CODE REVIEW

**Comment by bloubi** [comment]
Hi Marmelion,
thanks for your contributions, we gladly welcome German as a new language ! For legal reasons, we need you to authorize us to use your contrib under Apache v2 Licence. We'll soon put an automatic CLA system in place, but in the meantime, can you send us the files (zipped is ok) by email (for instance at contact at francelabs . com ), stating in the email that you allow us to use the files under Apache v2 licence?
Sorry for the inconvenience, but it is must to guarantee the legal stability of Datafari. Note that this is not a replacement of your pull requests, this goes in parallel (and since you are pulling quite frequentely, just send us the email once you think you have finished the modifications :) ).
Regards,
Cedric

**Comment by marlemion** [comment]
Hi Cedric,

you're welcome. Thanks in return for this wonderful piece of software. I will send you the email asap. Furthermore, I have modified the remaining json files to include German and corrected some errors and typos in de.json. I am quite new to git/github: is this automatically included in this pull request? Otherwise, I can create a new one.

**Comment by otavard** [comment]
Hi,
Thanks for your contribution.
Don't worry for your commits : they are well included in your pull request :)
After that we are OK for the Apache V2 licence, we will review the code and merge it gladly into Datafari.
Best regards,
Olivier

**Comment by otavard** [comment]
Hi marmelion,

We received your email with the Apache v2 licence agreement on the 02/07/17. Thanks for your contribution. It will be integrated very soon in Datafari 3.2 !

**Pull request merged**
