### PR TITLE
url.jsp

### PR DESCRIPTION
**Pull request by mrcpu1**
This jsp will allow the items that are returned int he search to be downloaded to your local client and displayed if your browser is set to open the specified file types by default. (i.e., if your browser is set to open .xls or .docx files then the file will be displayed otherwise it will download the file to your 'download' directory)

### CODE REVIEW

**Comment by amazoyer** [comment]
Hi!

Thank you for your contribution! Before merging your code, I want to do the following modification to Datafari:
- use the redirect URL current mecanism if the system is not able to read the file with your local read file mechanism (for example if we crawled a web site)
- add an option in datafari.properties in order to enable/disable the possibility to use your mechanism

We now have two branches for Datafari : the master branch is now used for new developments and the stable branch is used for new releases. Could you please create a new pull request to the master branch instead of the stable one?

Thank you again,

Aurélien

**Comment by mrcpu1** [comment]
Hi Aurelien,

That sounds great.   I'll go ahead and create a new pull request to the master branch,

Thank you,
Rick

On Feb 16, 2015, at 8:21 AM, amazoyer <notifications@github.com> wrote:

> Hi!
> 
> Thank you for your contribution! Before merging your code, I want to do the following modification to Datafari:
> 
> use the redirect URL current mecanism if the system is not able to read the file with your local read file mechanism (for example if we crawled a web site)
> add an option in datafari.properties in order to enable/disable the possibility to use your mechanism
> We now have two branches for Datafari : the master branch is now used for new developments and the stable branch is used for new releases. Could you please create a new pull request to the master branch instead of the stable one?
> 
> Thank you again,
> 
> Aurélien
> 
> —
> Reply to this email directly or view it on GitHub.
> 


-- 
This message has been scanned for viruses and
dangerous content by MailScanner, and is
believed to be clean.

**Comment by amazoyer** [comment]
Hi Rick,

Could you please create the new pull request to the master branch so I can do the merge?

Thanks :-),

Aurélien

**Comment by mrcpu1** [comment]
Hi Aurélien

I created the new pull request.  Let me know if I did it incorrectly, :)

Thank you,
Rick

**Pull request closed without merging**
